[[redirects]]
  from = "/api/*"
  to = "http://109.106.244.200:3800/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
